package gtp

var (
    GTPV1_MSG_ECHO_REQUEST = NewGTPv1Message(1, "GTPV1_MSG_ECHO_REQUEST", "Echo Request", []*GTPIE{}, GTPV1_MSG_ECHO_REPLY)
    GTPV1_MSG_ECHO_REPLY = NewGTPv1Message(2, "GTPV1_MSG_ECHO_REPLY", "Echo Response", []*GTPIE{GTPV2_IE_RECOVERY}, nil)
    GTPV1_MSG_VERSION_NOT_SUPPORTED = NewGTPv1Message(3, "GTPV1_MSG_VERSION_NOT_SUPPORTED", "Version Not Supported Indication", []*GTPIE{}, nil)
    GTPV1_MSG_CREATE_SESSION_REQUEST = NewGTPv1Message(32, "GTPV1_MSG_CREATE_SESSION_REQUEST", "Create Session Request", []*GTPIE{}, GTPV1_MSG_CREATE_SESSION_REPLY)
    GTPV1_MSG_CREATE_SESSION_REPLY = NewGTPv1Message(33, "GTPV1_MSG_CREATE_SESSION_REPLY", "Create Session Request", []*GTPIE{}, nil)
    GTPV1_MSG_MODIFY_BEARER_REQUEST = NewGTPv1Message(34, "GTPV1_MSG_MODIFY_BEARER_REQUEST", "Modify Bearer Request", []*GTPIE{}, GTPV1_MSG_MODIFY_BEARER_RESPONSE)
    GTPV1_MSG_MODIFY_BEARER_RESPONSE = NewGTPv1Message(35, "GTPV1_MSG_MODIFY_BEARER_RESPONSE", "Modify Bearer Response", []*GTPIE{}, nil)
)
