package gtp

var (
    GTPV2_MSG_ECHO_REQUEST = NewGTPv2Message(1, "GTPV2_MSG_ECHO_REQUEST", "Echo Request", []*GTPIE{GTPV2_IE_RECOVERY}, GTPV2_MSG_ECHO_REPLY)
    GTPV2_MSG_ECHO_REPLY = NewGTPv2Message(2, "GTPV2_MSG_ECHO_REPLY", "Echo Response", []*GTPIE{GTPV2_IE_RECOVERY}, nil)
    GTPV2_MSG_VERSION_NOT_SUPPORTED = NewGTPv2Message(3, "GTPV2_MSG_VERSION_NOT_SUPPORTED", "Version Not Supported Indication", []*GTPIE{}, nil)
    GTPV2_MSG_CREATE_SESSION_REQUEST = NewGTPv2Message(32, "GTPV2_MSG_CREATE_SESSION_REQUEST", "Create Session Request", []*GTPIE{}, GTPV2_MSG_CREATE_SESSION_REPLY)
    GTPV2_MSG_CREATE_SESSION_REPLY = NewGTPv2Message(33, "GTPV2_MSG_CREATE_SESSION_REPLY", "Create Session Request", []*GTPIE{}, nil)
    GTPV2_MSG_MODIFY_BEARER_REQUEST = NewGTPv2Message(34, "GTPV2_MSG_MODIFY_BEARER_REQUEST", "Modify Bearer Request", []*GTPIE{}, GTPV2_MSG_MODIFY_BEARER_RESPONSE)
    GTPV2_MSG_MODIFY_BEARER_RESPONSE = NewGTPv2Message(35, "GTPV2_MSG_MODIFY_BEARER_RESPONSE", "Modify Bearer Response", []*GTPIE{}, nil)
)
