// Code generated by "stringer -type=InstanceStatusCode"; DO NOT EDIT

package gtp

import "fmt"

const _InstanceStatusCode_name = "STATUS_OKSTATUS_TIMEOUTSTATUS_ERROR"

var _InstanceStatusCode_index = [...]uint8{0, 9, 23, 35}

func (i InstanceStatusCode) String() string {
	i -= 1
	if i >= InstanceStatusCode(len(_InstanceStatusCode_index)-1) {
		return fmt.Sprintf("InstanceStatusCode(%d)", i+1)
	}
	return _InstanceStatusCode_name[_InstanceStatusCode_index[i]:_InstanceStatusCode_index[i+1]]
}
