// Code generated by "stringer -type=InstanceMessageCode"; DO NOT EDIT

package gtp

import "fmt"

const _InstanceMessageCode_name = "SEND_MESSAGESEND_MESSAGE_REPLYNODE_MESSAGE_RECEIVEDNODE_MESSAGE_SENDNODE_MESSAGE_SEND_REPLYNODE_MESSAGE_SETUP_RETRYNODE_MESSAGE_TIMEOUT"

var _InstanceMessageCode_index = [...]uint8{0, 12, 30, 51, 68, 91, 115, 135}

func (i InstanceMessageCode) String() string {
	i -= 1
	if i >= InstanceMessageCode(len(_InstanceMessageCode_index)-1) {
		return fmt.Sprintf("InstanceMessageCode(%d)", i+1)
	}
	return _InstanceMessageCode_name[_InstanceMessageCode_index[i]:_InstanceMessageCode_index[i+1]]
}
